image: maven:3.9.9-eclipse-temurin-17

stages:
  - build
  - test
  - package
  - docker

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "-B -V --no-transfer-progress"

build-job:
  stage: build
  tags: [hva]
  script:
    - mvn $MAVEN_CLI_OPTS -DskipTests clean compile
  rules:
    - exists:
        - pom.xml

test-job:
  stage: test
  tags: [hva]
  script:
    - mvn $MAVEN_CLI_OPTS test

package-job:
  stage: package
  tags: [hva]
  script:
    - mvn $MAVEN_CLI_OPTS -DskipTests package
  artifacts:
    when: always
    paths:
      - target/*.jar
    expire_in: 1 week